_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  NUM_PROPOSALS: 500
  NUM_CLASSES: 24
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: (60000,)
  MAX_ITER: 65000
TEST:
  EVAL_PERIOD: 65000
  PREV_INTRODUCED_CLS: 17
  CUR_INTRODUCED_CLS: 6
  PREV_CLASSES: (10, 7,)
  MASK: 2
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
