_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  NUM_PROPOSALS: 500
  NUM_CLASSES: 81
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: (35000, 38000)
  MAX_ITER: 40000  # increased to keep similar training epochs
TEST:
  EVAL_PERIOD: 40000
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 19
  SCORE_THRESH: 0.
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
