_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  NUM_PROPOSALS: 500
  NUM_CLASSES: 81
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: (80000,)
  MAX_ITER: 85000
TEST:
  EVAL_PERIOD: 85000
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20
  PREV_CLASSES: (19, 21,)
  MASK: 2
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
